Create user crud
wolox-training/jw-java pull request #8
Opened 2020-08-20 21:33 UTC by juanwongramirez

## Summary

- Add UserController
- Add UserIdMismatchException
- Add UserNotFoundException
- Create addBook and removeBook methods in UserController

## Trello Card

https://trello.com/c/FTFnTD0m

2020-08-21 15:44 UTC, jeymarsonwolox requested changes

2020-08-21 15:44 UTC, jeymarsonwolox commented on src/main/java/wolox/training/controllers/UserController.java
> +                        String.format(Constants.FORMAT_MESSSAGE_BOOK_NOT_FOUND,id)));
same

2020-08-21 15:44 UTC, jeymarsonwolox commented on src/main/java/wolox/training/controllers/UserController.java
> +                        String.format(Constants.FORMAT_MESSSAGE_BOOK_NOT_FOUND,id)));
replace by `FORMAT_MESSSAGE_USER_NOT_FOUND`

2020-08-21 16:34 UTC, juanwongramirez commented on src/main/java/wolox/training/controllers/UserController.java
> +                        String.format(Constants.FORMAT_MESSSAGE_BOOK_NOT_FOUND,id)));
The changes has been loaded

2020-08-24 13:50 UTC, Jimenarosello requested changes
Very nice work! Just a couple of small adjustments and it should be good to go 🙂

2020-08-24 13:50 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UserController.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
Remember to use your custom exception here 😅

2020-08-24 13:50 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UserController.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
Same here!

2020-08-24 14:26 UTC, juanwongramirez commented on src/main/java/wolox/training/controllers/UserController.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
i have added custom exceptions

2020-08-24 20:19 UTC, jeymarsonwolox approved these changes

2020-08-26 16:05 UTC, Jimenarosello commented on src/main/java/wolox/training/utils/Constants.java
> +    public static String MESSSAGE_USER_ID_MISSMATCH = "The id value of user is not the same of the parameter";
There's a typo in the word `Message` 😅

2020-08-26 16:05 UTC, Jimenarosello approved these changes
Nice job! just a typo hehe 🚀

2020-08-27 21:28 UTC, merged