Add validations preconditions
wolox-training/jw-java pull request #9
Opened 2020-08-20 22:31 UTC by juanwongramirez

## Summary

- Add precondition in not null fields of User and Book models using guava

## Trello card

https://trello.com/c/WKypnkjX

2020-08-21 15:46 UTC, jeymarsonwolox requested changes
replace master with create-user-CRUD in source branch

2020-08-24 14:06 UTC, Jimenarosello requested changes
Just a few comments and it should be ready! 🚀

2020-08-24 14:06 UTC, Jimenarosello commented on src/main/java/wolox/training/utils/Constants.java
> +    public static String getValidationMessage(String field){
Maybe you can rename this method since it's specific for null and empty fields, and name it something like `getNullOrEmptyValidationMessage`, I think it would be more clear that way 😊

2020-08-24 14:06 UTC, Jimenarosello commented on src/main/java/wolox/training/models/User.java
> +                , "Must add at least one book");
The message constants that aren't covered by the `getValidationMessage` method should be included in the `Constants` class by themselves :) (the birthdate and pages validation messages too)

2020-08-24 14:06 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +        Preconditions.checkArgument(genre != null && !genre.isEmpty()
Check out [this method by Guava](https://guava.dev/releases/27.1-jre/api/docs/com/google/common/base/Strings.html#isNullOrEmpty-java.lang.String- )
It's cool for null and empty checks with Strings 😄 (just a suggestion for the future)

2020-08-26 15:54 UTC, Jimenarosello approved these changes

2020-08-26 18:45 UTC, jeymarsonwolox approved these changes

2020-08-27 21:29 UTC, merged